- migration-tools/scripts/post-migration.sh
https://github.com/arangodb/docs/pull/1280
> Monitoring folder removed in 3.10+

- PULL_REQUEST_TEMPLATE.md
- github-app/arangodb-docs-automation/app.yml
- github-app/arangodb-docs-automation/index.js
THIS IS THE PULL REQUEST DESCRIPTION
Here there will be the CI Trigger config
> Test Probot Pull Request open event

- .circleci/commit.js
- .circleci/config.yml
<br>
<br>
- 3.10:
- 3.11:
- 3.12:
- devel:
> [DOC-496] New commit strategy

- site/themes/arangodb-docs-theme/static/js/theme.js
<br>
<br>
- 3.10:
- 3.11:
- 3.12:
- devel:
> [DOC-497] Do not generate Table Of Contents when not enough headers

- .circleci/config.yml
- .circleci/utils.sh
<br>
<br>
- 3.10:
- 3.11:
- 3.12:
- devel:
> Improve CircleCI

- toolchain/scripts/toolchain.sh
<br>
<br>
- 3.10:
- 3.11:
- 3.12:
- devel:
> toolchain script refactor

- migration-tools/scripts/http_docublocks.py
- migration-tools/scripts/inline_docublocks.py
- site/themes/arangodb-docs-theme/layouts/partials/shortcodes/examples/example.html
- site/themes/arangodb-docs-theme/layouts/partials/shortcodes/examples/generate.html
- toolchain/arangoproxy/internal/cache.go
- toolchain/arangoproxy/internal/init.go
- toolchain/arangoproxy/internal/models/example.go
- toolchain/arangoproxy/internal/models/repository.go
- toolchain/arangoproxy/internal/service/service.go
- toolchain/docker/amd64/docker-compose.plain-build.yml
- toolchain/docker/arm64/docker-compose.plain-build.yml
- toolchain/docker/config.yaml
- toolchain/scripts/toolchain.sh
…es for tracking
<br>
<br>
- 3.10:
- 3.11:
- 3.12:
- devel:
> Minimal examples metadata and better docker containers managing

- site/themes/arangodb-docs-theme/layouts/partials/search.html
> fix: use version to filter the search

- site/themes/arangodb-docs-theme/layouts/partials/search.html
> fix: pass the correct facet filter 

- site/themes/arangodb-docs-theme/layouts/partials/shortcodes/expand.html
- site/themes/arangodb-docs-theme/layouts/shortcodes/program-options.html
> Fix startup-options rendering errors

- site/themes/arangodb-docs-theme/layouts/partials/toc.html
> Adjust Contribute link repository

- site/themes/arangodb-docs-theme/static/css/theme.css
> fix css not showing anchors for h3 onwards

- CIRCLECI.md
> Add CircleCI instructions

- site/content/3.10/get-started/how-to-interact-with-arangodb.md
- site/content/3.10/get-started/on-premises-installation.md
- site/content/3.10/get-started/overview.md
- site/content/3.10/index-and-search/indexing/_index.md
- site/content/3.10/operations/security/_index.md
- site/content/3.11/get-started/how-to-interact-with-arangodb.md
- site/content/3.11/get-started/on-premises-installation.md
- site/content/3.11/get-started/overview.md
- site/content/3.11/index-and-search/indexing/_index.md
- site/content/3.11/operations/security/_index.md
- site/content/3.12/get-started/how-to-interact-with-arangodb.md
- site/content/3.12/get-started/on-premises-installation.md
- site/content/3.12/get-started/overview.md
- site/content/3.12/index-and-search/indexing/_index.md
- site/content/3.12/operations/security/_index.md
> Add descriptions in empty cards

- site/content/3.10/aql/_index.md
- site/content/3.10/develop/http/_index.md
- site/content/3.11/aql/_index.md
- site/content/3.11/develop/http/_index.md
- site/content/3.12/aql/_index.md
- site/content/3.12/develop/http/_index.md
- site/data/versions.yaml
> delete {{ pageVersion }} from titles

- site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
> DOC-555 | Release notes for in-memory cache subsystem 3.11.4

- site/content/3.10/deploy/deployment/kubernetes/backuppolicy-resource.md
- site/content/3.11/deploy/deployment/kubernetes/backuppolicy-resource.md
- site/content/3.12/deploy/deployment/kubernetes/backuppolicy-resource.md
Update documentation for ArangoBackupPolicy CR:
- better formatting for examples
- new example for maxBackups feature
- two new fields described
> Update docs for ArangoBackupPolicy

- .circleci/base_config.yml
- .circleci/generate_config.py
> [DOC-566] Release approval step only for generated release

- site/content/3.10/aql/high-level-operations/with.md
- site/content/3.10/release-notes/version-3.10/incompatible-changes-in-3-10.md
- site/content/3.11/aql/high-level-operations/with.md
- site/content/3.11/release-notes/version-3.10/incompatible-changes-in-3-10.md
- site/content/3.12/aql/high-level-operations/with.md
- site/content/3.12/release-notes/version-3.10/incompatible-changes-in-3-10.md
- site/themes/arangodb-docs-theme/layouts/_default/_markup/render-link.html
> DOC-558 | Start vertex collections may need to be declared using `WITH`

- site/content/3.10/develop/integrations/spring-data-arangodb/_index.md
- site/content/3.11/develop/integrations/spring-data-arangodb/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/_index.md
Clarify which versions of Spring Boot are compatible with each version of Spring Data ArangoDB.
> Clarify Spring Data supported versions

- toolchain/scripts/toolchain.sh
> [DOC-598] Remove oasisctl from release workflow

- .circleci/base_config.yml
- .circleci/generate_config.py
> Fix Compile docker image version

- toolchain/scripts/generators/oasisctl.py
> [DOC-616] OasisCTL generator adjustments

- site/content/3.10/develop/drivers/java/_index.md
- site/content/3.10/develop/drivers/java/reference-version-7/_index.md
- site/content/3.10/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.10/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.11/develop/drivers/java/_index.md
- site/content/3.11/develop/drivers/java/reference-version-7/_index.md
- site/content/3.11/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.12/develop/drivers/java/_index.md
- site/content/3.12/develop/drivers/java/reference-version-7/_index.md
- site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
Documentation for the asynchronous API introduced in the Java Driver version 7.2.
> [DE-714] Java Driver: asynchronous API

- site/content/3.10/components/tools/arangobackup/examples.md
- site/content/3.11/components/tools/arangobackup/examples.md
- site/content/3.12/components/tools/arangobackup/examples.md
> DOC-615 | Views are part of hot backups since v3.6.0

- site/themes/arangodb-docs-theme/static/css/theme.css
> DOC-622 | Fix logo positioning

- site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Added release notes.
- 3.10:
- 3.11: https://github.com/arangodb/arangodb/pull/20067
- 3.12: https://github.com/arangodb/arangodb/pull/20036
> Add release notes for detached scheduler threads

- .circleci/generate_config.py
- 3.10: 
- 3.11:
- 3.12: https://github.com/arangodb/arangodb/pull/20138
**DONT /commit**, the generation was only for testing purposes
> Fix generate workflow for enterprise-preview images with regards to OpenSSL

- site/content/3.10/arangograph/deployments/_index.md
- site/content/3.11/arangograph/deployments/_index.md
- site/content/3.12/arangograph/deployments/_index.md
Added in the Edit deployment section info about:
- scaling down deployments
- upgrading Single Server deployments to OneShard or Sharded
> DOC-619 | ArangoGraph: scale down deployment, upgrade single server

- site/content/3.10/develop/integrations/kafka-connect-arangodb-sink-connector/configuration.md
- site/content/3.11/develop/integrations/kafka-connect-arangodb-sink-connector/configuration.md
- site/content/3.12/develop/integrations/kafka-connect-arangodb-sink-connector/configuration.md
Added connections rebalance interval configuration for Kafka Connector.
> [DE-662] Kafka Connector: connections rebalance configuration

- site/content/3.10/deploy/cluster/administration.md
- site/content/3.11/deploy/cluster/administration.md
- site/content/3.12/deploy/cluster/administration.md
Fix old instructions for Shard rebalance button in the web interface.
- 3.10:
- 3.11:
- 3.12:
> Fix old instructions for Shard rebalance UI button

- site/content/3.12/aql/high-level-operations/search.md
Can overload system. PR needs more specific information!
- 3.10:
- 3.11:
- 3.12:
> Add remark about high SEARCH `parallelism`

- site/content/3.10/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
- site/content/3.11/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
- site/content/3.12/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
Kafka Connector: removed limitation about VST.
> [DE-619] Kafka Connector: removed limitation about VST

- site/content/3.10/release-notes/version-3.10/whats-new-in-3-10.md
- site/content/3.11/release-notes/version-3.10/whats-new-in-3-10.md
- site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.10/whats-new-in-3-10.md
- site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
> Release notes: Detached scheduler threads

- site/content/3.10/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
- site/content/3.10/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
- site/content/3.11/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
- site/content/3.11/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
Spring Data: added documentation to customize auditing
> Spring Data: added documentation to customize auditing

- site/content/3.10/release-notes/version-3.10/api-changes-in-3-10.md
- site/content/3.10/release-notes/version-3.10/incompatible-changes-in-3-10.md
- site/content/3.11/release-notes/version-3.10/api-changes-in-3-10.md
- site/content/3.11/release-notes/version-3.10/incompatible-changes-in-3-10.md
- site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
- site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
- site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
- site/content/3.12/release-notes/version-3.10/incompatible-changes-in-3-10.md
- site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
- site/content/3.12/release-notes/version-3.11/incompatible-changes-in-3-11.md
- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
> Add `smartGraphAttribute` validation behavior change

- site/content/3.10/data-science/arangographml/getting-started.md
- site/content/3.11/data-science/arangographml/getting-started.md
- site/content/3.12/data-science/arangographml/getting-started.md
Branched off of #419 
Decorates the `getting-started` sections with links to https://arangoml.github.io/arangoml/
- 3.10:
- 3.11:
- 3.12:
> add specification hyperlinks

- site/content/3.10/develop/integrations/spring-data-arangodb/_index.md
- site/content/3.11/develop/integrations/spring-data-arangodb/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/_index.md
documented configuration for VPACK content type
> [DE-707] Spring Data: documented configuration for VPACK content type

- site/content/3.10/data-science/adapters/arangodb-rdf-adapter.md
- site/content/3.11/data-science/adapters/arangodb-rdf-adapter.md
- site/content/3.12/data-science/adapters/arangodb-rdf-adapter.md
ref: https://github.com/arangodb/docs-hugo/pull/439#discussion_r1467992850
> fix ArangoRDF typo

- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
https://github.com/arangodb/arangodb/pull/20038
- 3.10:
- 3.11:
- 3.12:
> DOC-614 | BTS-1661 - Different errors for vertex collection not in graph

- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Relates to https://github.com/arangodb/arangodb/pull/20568
> DOC-614 | Add release notes: compression for cluster-internal traffic

- site/content/3.10/arangograph/deployments/upgrades-and-versioning.md
- site/content/3.11/arangograph/deployments/upgrades-and-versioning.md
- site/content/3.12/arangograph/deployments/upgrades-and-versioning.md
> DOC-662 | Version upgrades in ArangoGraph

- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- https://github.com/arangodb/arangodb/pull/20493
- https://github.com/arangodb/arangodb/pull/20492
- 3.10:
- 3.11:
- 3.12:
> DOC-614 | Batch materialize with projections

- site/content/3.10/release-notes/version-3.10/whats-new-in-3-10.md
- site/content/3.11/release-notes/version-3.10/whats-new-in-3-10.md
- site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.10/whats-new-in-3-10.md
- site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Related PRs:
- https://github.com/arangodb/arangodb/pull/20667 (3.10)
- https://github.com/arangodb/arangodb/pull/20666 (3.11)
- https://github.com/arangodb/arangodb/pull/20663 (3.12)
- https://github.com/arangodb/arangodb/pull/20664 (3.12.0)
- 3.10:
- 3.11:
- 3.12:
> arangodump: Document experimental parallel dump for 3.10 and 3.11

- site/content/3.12/develop/http-api/transactions/javascript-transactions.md
- site/content/3.12/develop/transactions/_index.md
- site/content/3.12/develop/transactions/javascript-transactions.md
- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
> DOC-672 | Add deprecation remarks for JavaScript Transactions

- site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
Java driver updates for ArangoDB 3.12
> [DE-782] Java driver updates for ArangoDB 3.12 

- site/content/3.10/arangograph/security-and-access-control/_index.md
- site/content/3.11/arangograph/security-and-access-control/_index.md
- site/content/3.12/arangograph/security-and-access-control/_index.md
- site/content/4.0/arangograph/security-and-access-control/_index.md
Added a note on enabling Audit Log on AG.
- 3.10: 
- 3.11: 
- 3.12: 
- 4.0:
> DOC-675: Note about enabling Audit log on AG

- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- site/content/4.0/release-notes/version-3.12/whats-new-in-3-12.md
Added info about an upgraded rclone version to 3.12 Release Notes.
> DOC-676 rclone version

- site/content/3.10/arangograph/oasisctl/_index.md
- site/content/3.11/arangograph/oasisctl/_index.md
- site/content/3.12/arangograph/oasisctl/_index.md
- site/content/3.13/arangograph/oasisctl/_index.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> updates ArangoGraph API link

- site/content/3.10/data-science/arangographml/getting-started.md
- site/content/3.11/data-science/arangographml/getting-started.md
- site/content/3.12/data-science/arangographml/getting-started.md
- site/content/3.13/data-science/arangographml/getting-started.md
Documentation updates to reflect ML V1 API Changes.
Happy to address any recommendations/feedback!
Related to:
- https://github.com/arangoml/notebook-images/pull/132
- https://github.com/arangoml/arangoml/pull/68
> MLP-658 | ML V1 updates

- site/content/3.12/operations/installation/docker.md
- site/content/3.13/operations/installation/docker.md
- Update of official Docker Hub image README:
https://github.com/docker-library/docs/pull/2449 (@KVS85 please approve)
- Update arangodb/arangodb README: Who can do this? I lack the permissions
https://hub.docker.com/repository/docker/arangodb/arangodb/general (very bottom)
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-681 | How to initialize server language using Docker containers

- site/content/3.10/develop/drivers/java/_index.md
- site/content/3.10/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.11/develop/drivers/java/_index.md
- site/content/3.11/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.12/develop/drivers/java/_index.md
- site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.13/develop/drivers/java/_index.md
- site/content/3.13/develop/drivers/java/reference-version-7/changes-in-version-7.md
> Java Driver: added Helidon example

- site/content/3.10/data-science/arangographml/getting-started.md
- site/content/3.11/data-science/arangographml/getting-started.md
- site/content/3.12/data-science/arangographml/getting-started.md
- site/content/3.13/data-science/arangographml/getting-started.md
Minor cleanup to ML documentation
> update ml docs

- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-667 | arangodump retries on read, write, and connection errors

- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-667 | Log queue overwhelm metric

- site/content/3.12/develop/http-api/monitoring/logs.md
- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.13/develop/http-api/monitoring/logs.md
- site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
- https://github.com/arangodb/arangodb/pull/20963
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-667 | Add `DELETE /_admin/log/level` endpoint for resetting log levels

- site/content/3.10/data-science/arangographml/getting-started.md
- site/content/3.11/data-science/arangographml/getting-started.md
- site/content/3.12/data-science/arangographml/getting-started.md
- site/content/3.13/data-science/arangographml/getting-started.md
Fixing broken links for ArangoML documentation
> fix: arangoml doc refs

- site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
- site/content/3.13/release-notes/version-3.12/incompatible-changes-in-3-12.md
Addendum to #530
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-674 | Subquery evaluation: Add to Incompatible changes

- site/content/3.10/develop/integrations/spring-boot-arangodb.md
- site/content/3.11/develop/integrations/spring-boot-arangodb.md
- site/content/3.12/develop/integrations/spring-boot-arangodb.md
- site/content/3.13/develop/integrations/spring-boot-arangodb.md
Spring Boot Starter: updated current versions
> [DE-816] Spring Boot Starter: updated current versions

- site/content/3.10/develop/integrations/arangodb-datasource-for-apache-spark.md
- site/content/3.11/develop/integrations/arangodb-datasource-for-apache-spark.md
- site/content/3.12/develop/integrations/arangodb-datasource-for-apache-spark.md
- site/content/3.13/develop/integrations/arangodb-datasource-for-apache-spark.md
Spark Datasource: TLS hostname verification
> [DE-790] Spark Datasource: TLS hostname verification

- site/content/3.10/develop/integrations/arangodb-datasource-for-apache-spark.md
- site/content/3.11/develop/integrations/arangodb-datasource-for-apache-spark.md
- site/content/3.12/develop/integrations/arangodb-datasource-for-apache-spark.md
- site/content/3.13/develop/integrations/arangodb-datasource-for-apache-spark.md
Spark Datasource: added HTTP2 protocol
> [DE-596] Spark Datasource: added HTTP2 protocol

- site/content/3.10/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
- site/content/3.11/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
- site/content/3.12/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
- site/content/3.13/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
Kafka Connector: documented connection handling
> [DE-799] Kafka Connector: documented connection handling

- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-667 | Add release notes for 3.12.1 metrics

- site/content/3.11/about-arangodb/features/_index.md
- site/content/3.11/arangograph/_index.md
- site/content/3.11/arangograph/api/get-started.md
- site/content/3.11/arangograph/deployments/private-endpoints.md
- site/content/3.11/arangograph/security-and-access-control/x-509-certificates.md
- site/content/3.11/deploy/_index.md
- site/content/3.11/deploy/cluster/deployment/_index.md
- site/content/3.11/get-started/set-up-a-cloud-instance.md
- site/content/3.12/about-arangodb/features/_index.md
- site/content/3.12/arangograph/_index.md
- site/content/3.12/arangograph/api/get-started.md
- site/content/3.12/arangograph/deployments/private-endpoints.md
- site/content/3.12/arangograph/security-and-access-control/x-509-certificates.md
- site/content/3.12/deploy/_index.md
- site/content/3.12/deploy/cluster/deployment/_index.md
- site/content/3.12/get-started/set-up-a-cloud-instance.md
- site/content/3.13/about-arangodb/features/_index.md
- site/content/3.13/arangograph/_index.md
- site/content/3.13/arangograph/api/get-started.md
- site/content/3.13/arangograph/deployments/private-endpoints.md
- site/content/3.13/arangograph/security-and-access-control/x-509-certificates.md
- site/content/3.13/deploy/_index.md
- site/content/3.13/deploy/cluster/deployment/_index.md
- site/content/3.13/get-started/set-up-a-cloud-instance.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-706: remove Azure from AG documentation

- site/content/3.10/data-science/adapters/arangodb-cugraph-adapter.md
- site/content/3.10/data-science/adapters/arangodb-networkx-adapter.md
- site/content/3.11/data-science/adapters/arangodb-cugraph-adapter.md
- site/content/3.11/data-science/adapters/arangodb-networkx-adapter.md
- site/content/3.12/data-science/adapters/arangodb-cugraph-adapter.md
- site/content/3.12/data-science/adapters/arangodb-networkx-adapter.md
- site/content/3.13/data-science/adapters/arangodb-cugraph-adapter.md
- site/content/3.13/data-science/adapters/arangodb-networkx-adapter.md
Adding a `< tip >` bar to the NetworkX & cuGraph Adapter pages to point to https://arangodb.com/introducing-the-arangodb-networkx-persistence-layer/
> new: `nx-arangodb` tip bar

- site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.13/develop/drivers/java/reference-version-7/driver-setup.md
Added serde provider class configuration
> [DE-837] Java Driver: serde provider class configuration

- site/content/3.11/arangograph/data-loader/_index.md
- site/content/3.11/components/tools/arango-datasets.md
- site/content/3.11/concepts/data-structure/databases.md
- site/content/3.11/data-science/arangographml/getting-started.md
- site/content/3.11/data-science/graph-analytics.md
- site/content/3.12/arangograph/data-loader/_index.md
- site/content/3.12/components/tools/arango-datasets.md
- site/content/3.12/concepts/data-structure/databases.md
- site/content/3.12/data-science/arangographml/getting-started.md
- site/content/3.12/data-science/graph-analytics.md
- site/content/3.12/develop/http-api/monitoring/logs.md
- site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- site/content/3.13/arangograph/data-loader/_index.md
- site/content/3.13/components/tools/arango-datasets.md
- site/content/3.13/concepts/data-structure/databases.md
- site/content/3.13/data-science/arangographml/getting-started.md
- site/content/3.13/data-science/graph-analytics.md
- site/content/3.13/develop/http-api/monitoring/logs.md
- site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
- site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md
- Fix collections -> databases
- Replace tabs with list because using enumerations breaks the layout
- Fix OpenAPI validation warning
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Fix typo, broken tab layout, query param default

- .circleci/base_config.yml
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> added new keys

- site/content/3.11/develop/drivers/java/_index.md
- site/content/3.11/develop/drivers/java/reference-version-6/_index.md
- site/content/3.11/develop/drivers/java/reference-version-6/driver-setup.md
- site/content/3.11/develop/drivers/java/reference-version-6/serialization.md
- site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.12/develop/drivers/java/_index.md
- site/content/3.12/develop/drivers/java/reference-version-6/_index.md
- site/content/3.12/develop/drivers/java/reference-version-6/driver-setup.md
- site/content/3.12/develop/drivers/java/reference-version-6/serialization.md
- site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.13/develop/drivers/java/_index.md
- site/content/3.13/develop/drivers/java/reference-version-6/_index.md
- site/content/3.13/develop/drivers/java/reference-version-6/driver-setup.md
- site/content/3.13/develop/drivers/java/reference-version-6/serialization.md
- site/content/3.13/develop/drivers/java/reference-version-7/driver-setup.md
> [DE-573] Java Driver: v6 EOL

- site/content/3.12/develop/integrations/spring-data-arangodb/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/converter.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/document.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/edge.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/events.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/indexes.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/reference.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/relations.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/repositories/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/repositories/queries/_index.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/repositories/queries/derived-queries.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/repositories/queries/named-queries.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/repositories/queries/query-methods.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/template.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-4/mapping/document.md
- site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-4/mapping/relations.md
> [DE-763] Spring Data: v3 EOL

- site/content/3.11/develop/drivers/_index.md
- site/content/3.11/develop/drivers/go.md
- site/content/3.12/develop/drivers/_index.md
- site/content/3.12/develop/drivers/go.md
- site/content/3.13/develop/drivers/_index.md
- site/content/3.13/develop/drivers/go.md
@jwierzbo I made a couple of changes here before copying the content: https://github.com/arangodb/go-driver/pull/628/commits/692139a18f325fbdd480674fb410c5db712d3a49
Preview: https://deploy-preview-626--docs-hugo.netlify.app/stable/develop/drivers/go/
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-713 | Add Go driver v2 tutorial

- .circleci/generate_config.py
For testing:
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13: https://github.com/arangodb/arangodb/pull/20696
> CircleCI: Update ArangoDB 3.12+ build image tag to version 7

- site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.13/develop/drivers/java/reference-version-7/driver-setup.md
Java Driver HTTP proxy documentation.
> Java Driver: HTTP proxy

- .circleci/base_config.yml
- .circleci/generate_config.py
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> CircleCI: Update build images for 3.11 and 3.12/devel

- site/content/3.11/data-science/graph-analytics.md
- site/content/3.12/data-science/graph-analytics.md
- site/content/3.13/data-science/graph-analytics.md
- https://github.com/arangodb/gral/pull/65
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Graph analytics: Add betweenness-centrality algorithm

- site/content/3.10/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.11/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
- site/content/3.13/develop/drivers/java/reference-version-7/changes-in-version-7.md
Java Driver: made BaseDocument serializable again
> Java Driver: made BaseDocument serializable again

- site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
- site/content/3.12/release-notes/version-3.11/incompatible-changes-in-3-11.md
- site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
- site/content/3.13/release-notes/version-3.11/incompatible-changes-in-3-11.md
- site/content/3.13/release-notes/version-3.12/incompatible-changes-in-3-12.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-704 | Clarify that keys out-of-order can occur any time

- site/themes/arangodb-docs-theme/layouts/partials/inkeep-widget.html
- site/themes/arangodb-docs-theme/layouts/partials/tracking/body-end.html
- site/themes/arangodb-docs-theme/static/css/theme.css
Also revert adjustments for the Inkeep widget that were only necessary because of HubSpot
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Remove HubSpot integration

- site/content/3.11/develop/http-api/cluster.md
- site/content/3.12/develop/http-api/cluster.md
- site/content/3.13/develop/http-api/cluster.md
This is related to:
- https://github.com/arangodb/docs-hugo/pull/406
- https://github.com/arangodb/arangodb/pull/21685
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Structured description for `PUT /_admin/cluster/maintenance` request body

- site/content/3.12/about-arangodb/features/_index.md
- site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
- site/content/3.13/about-arangodb/features/_index.md
- site/content/3.13/release-notes/version-3.12/incompatible-changes-in-3-12.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-693 | Clarify license terms

- site/content/3.11/aql/fundamentals/syntax.md
- site/content/3.12/aql/fundamentals/syntax.md
- site/content/3.13/aql/fundamentals/syntax.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> AQL: Add missing links for operations' `OPTIONS` to keyword overview

- htmltest-external.yml
- site/content/3.11/components/arangodb-server/storage-engine.md
- site/content/3.11/data-science/llm-knowledge-graphs.md
- site/content/3.11/data-science/pregel/_index.md
- site/content/3.11/operations/installation/linux/_index.md
- site/content/3.12/components/arangodb-server/storage-engine.md
- site/content/3.12/data-science/llm-knowledge-graphs.md
- site/content/3.12/operations/installation/linux/_index.md
- site/content/3.13/components/arangodb-server/storage-engine.md
- site/content/3.13/data-science/llm-knowledge-graphs.md
- site/content/3.13/operations/installation/linux/_index.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Fix external links

- site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
- site/content/3.13/develop/drivers/java/reference-version-7/driver-setup.md
added Java Driver: pipelining configuration
> Java Driver: pipelining configuration

- site/content/3.11/aql/graphs/all-shortest-paths.md
- site/content/3.11/aql/graphs/k-paths.md
- site/content/3.11/aql/graphs/k-shortest-paths.md
- site/content/3.11/aql/graphs/shortest-path.md
- site/content/3.12/aql/graphs/all-shortest-paths.md
- site/content/3.12/aql/graphs/k-paths.md
- site/content/3.12/aql/graphs/k-shortest-paths.md
- site/content/3.12/aql/graphs/shortest-path.md
- site/content/3.13/aql/graphs/all-shortest-paths.md
- site/content/3.13/aql/graphs/k-paths.md
- site/content/3.13/aql/graphs/k-shortest-paths.md
- site/content/3.13/aql/graphs/shortest-path.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Improve lead paragraphs and text for AQL graph traversal and path search algorithms

- site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
- site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md
Already available in 3.12.5-2 hotfix.
- https://github.com/arangodb/arangodb/pull/21860
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-782 | Release notes for startup option to perform full RocksDB compaction on upgrade

- site/content/3.11/aql/fundamentals/query-errors.md
- site/content/3.11/aql/user-defined-functions.md
- site/content/3.11/develop/drivers/javascript.md
- site/content/3.11/develop/javascript-api/@arangodb/_index.md
- site/content/3.11/develop/transactions/javascript-transactions.md
- site/content/3.12/aql/execution-and-performance/query-logging.md
- site/content/3.12/aql/fundamentals/query-errors.md
- site/content/3.12/aql/user-defined-functions.md
- site/content/3.12/develop/drivers/javascript.md
- site/content/3.12/develop/javascript-api/@arangodb/_index.md
- site/content/3.12/develop/transactions/javascript-transactions.md
- site/content/3.13/aql/execution-and-performance/query-logging.md
- site/content/3.13/aql/fundamentals/query-errors.md
- site/content/3.13/aql/user-defined-functions.md
- site/content/3.13/develop/drivers/javascript.md
- site/content/3.13/develop/javascript-api/@arangodb/_index.md
- site/content/3.13/develop/transactions/javascript-transactions.md
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> Fix links to error-codes page

- site/content/3.12/develop/http-api/cluster.md
- site/content/3.13/develop/http-api/cluster.md
- https://github.com/arangodb/arangodb/pull/21913
TODO: Add known issue and link to the new endpoint?
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:
> DOC-794 | HTTP API: Endpoint for reserving/skipping globally unique IDs
