arangodb/docs-hugo

BUILD.md
site/config/frontend/params.yaml
toolchain/docker-env/frontend.env
toolchain/scripts/functions.sh

It has arangoproxy disabled to skip example generation to speed up the build time, which is useful for working on the theme

Add a frontend environment file

---

toolchain/scripts/toolchain.sh

To test:
Make sure swagger-cli is installed. (For the moment, later the toolchain script will be dockerized so no host dependencies).
Launch ./toolchain.sh {version} generate-apidocs
The toolchain will generate the api-docs file in the path set in the toolchain/scripts/config.yaml at the key apidocs.
After generating the file, swagger-cli validate {file} will be launched to validate the generated schema.

[DOC-424] Validate the schema generated from generateApiDocs script

---

migration-tools/scripts/automata.py
migration-tools/scripts/migrate_file.py
site/config/_default/config.yaml
site/data/versions.yaml
site/themes/hugo-theme-relearn/layouts/partials/_main.hugo
site/themes/hugo-theme-relearn/layouts/partials/archetypes/chapter/article.html
site/themes/hugo-theme-relearn/layouts/partials/archetypes/default/article.html
site/themes/hugo-theme-relearn/layouts/partials/archetypes/home/article.html
site/themes/hugo-theme-relearn/layouts/partials/archetypes/label/article.html
site/themes/hugo-theme-relearn/layouts/partials/deprecated.html
site/themes/hugo-theme-relearn/layouts/partials/header.html
site/themes/hugo-theme-relearn/layouts/partials/in-development.html
site/themes/hugo-theme-relearn/layouts/partials/menu.html
site/themes/hugo-theme-relearn/layouts/partials/shortcodes/version.html
site/themes/hugo-theme-relearn/layouts/shortcodes/error-codes.html
site/themes/hugo-theme-relearn/layouts/shortcodes/metrics.html
site/themes/hugo-theme-relearn/layouts/shortcodes/version.html
site/themes/hugo-theme-relearn/static/css/theme.css

**NOTE: This PR includes the DOC-448 task about metrics rendering as they are interdependent.**
A version partial has been created to assign a "pageVersion" variable to each page during build time.
The "pageVersion" variable of a page is available at {{ .Page.Scratch.Get "pageVersion" }} at any time.
The version is set by matching the page path (e.g. /3.10/...../page) against the site/data/versions.yaml file, if one of the entries has name: {pagePathFirstFolder -> e.g. 3.10), the version: value of that entry is assigned to the page.
Page can have {{ pageVersion }} variable in the title front matter that is expanded using the pageVersion variable of the page.

[DOC-430][DOC-448] versions.yaml and version variable in pages, metrics migration and rendering

---

toolchain/scripts/generators/generateApiDocs.py

The generateApiDocs script has to move the # headers in the openapi codeblocks as summary fields.

[DOC-429] Convert openapi headers in summary field

---

site/themes/arangodb-docs-theme/layouts/partials/breadcrumbs.html
site/themes/arangodb-docs-theme/layouts/partials/content-footer.html
site/themes/arangodb-docs-theme/layouts/partials/meta.html

Any pointer to {version}/_index.md page is now redirected to {version}/introduction.
Affected items are url entry, breadcrumb link and footer navigation
- 3.10:
- 3.11:
- 3.12:

Hide version index page

---

.circleci/config.yml
toolchain/arangoproxy/internal/arangosh/arangosh.go
toolchain/arangoproxy/internal/controller.go
toolchain/arangoproxy/internal/models/example.go
toolchain/arangoproxy/internal/models/logger.go
toolchain/arangoproxy/internal/service/service.go
toolchain/scripts/toolchain.sh

This PR brings following features:
- The toolchain won't immediately fail as soon as an example fails validation. 
Instead, the failing examples will be tracked down into the summary.md. The toolchain will fail with message in post-build.
- The summary.md contains stacktrace, filepath and starting line of failing example.
- Centralized all containers logs into a single toolchain.log file
- Enhanced handling of async exit of any toolchain container.
- A predefined exit status of the toolchain so to understand immediately the macro cause of error (e.g. 2=api-docs, 3=examples, 4=metrics and so on)
- 3.10:
- 3.11:
- 3.12:

[DOC-528] Toolchain Errors Handling, Logs

---

site/themes/arangodb-docs-theme/layouts/partials/meta.html

Set `docsearch:version` in `<meta>`, fix /hooks/ redirect

---

site/themes/arangodb-docs-theme/layouts/_default/home.navigation.html
site/themes/arangodb-docs-theme/static/css/theme.css
site/themes/arangodb-docs-theme/static/js/theme.js

Cleaner implementation of the nav template with unused data removed.
Everything still seems to look and work the same, but the nav.html file size is down from 728 KB to 420 KB.
Additional savings are possible by not including the baseURL in links but this requires changes to the JavaScript code in multiple places.

Simplify navigation generation

---

site/themes/arangodb-docs-theme/static/js/theme.js

Content has been adjusted instead:
https://github.com/arangodb/docs/pull/1464

DOC-536 | Remove `moveTags()` function

---

README.md
migration-tools/scripts/automata.py

Also change label to ArangoDB Enterprise Edition and mention "Deprecated in: ..."

Clarify use of tags shortcode

---

site/themes/arangodb-docs-theme/layouts/partials/search.html

Added `maxResultsPerGroup` with a value of 10 to the search. 
- 3.10:
- 3.11:
- 3.12:

Add `maxResultsPerGroup` to search

---

site/config/_default/config.yaml
site/themes/arangodb-docs-theme/layouts/partials/head.html
site/themes/arangodb-docs-theme/static/js/theme.js

- Page titles can contain some Markdown. Now this gets rendered to HTML to then strip all HTML tags out for a plain title: `The _collection_ object` -> `The collection object`
- On soft navigation, the document.title now gets changed to the new page's title,
taking into account html entities (`&ldquo;` -> `“` etc.)
- Change separator for titles so that we now get `Title | ArangoDB Documentation` instead of `:: ArangoDB Documentation`

DOC-533 | Fix page titles

---

site/themes/arangodb-docs-theme/layouts/partials/version-selector.html
site/themes/arangodb-docs-theme/static/js/theme.js

Selecting either of the legacy version opens the old docs in a new tab. If this is blocked, the address of the current page is changed to the old docs.
The version selector value is reverted to stay in sync with what you actually see. Otherwise, you would click e.g. 3.9, it would open in a new tab, but the new docs would still you show e.g. 3.11 but the selector would be set to 3.9.
Note that there are still ways to get the version selector out of sync, which isn't addressed by this PR.

Add 3.9 and 3.8 to version selector

---

site/themes/arangodb-docs-theme/layouts/partials/search.html
site/themes/arangodb-docs-theme/static/js/theme.js

1. Initial localStorage version was not being set properly. Switched to using URL as a source of truth on initilization
2. On switching version, we need to re-initialize the search (as the page doesn’t reload). To fix, moved docsearch creation into a function & called that on switching
- 3.10:
- 3.11:
- 3.12:

fix: search version faceting

---

site/themes/arangodb-docs-theme/layouts/shortcodes/program-options.md

A startup option can be enabled without value if requiresValue != true
- 3.10:
- 3.11:
- 3.12:

Fix logic error in startup option rendering

---

site/content/3.10/arangograph/deployments/_index.md
site/content/3.10/arangograph/security-and-access-control/x-509-certificates.md
site/content/3.11/arangograph/deployments/_index.md
site/content/3.11/arangograph/security-and-access-control/x-509-certificates.md
site/content/3.12/arangograph/deployments/_index.md
site/content/3.12/arangograph/security-and-access-control/x-509-certificates.md

Add new default port `443` to ArangoGraph docs. Needs to be applied to 3.11 and 3.12.

ArangoGraph: Add new default port `443`

---

site/content/3.10/concepts/data-structure/databases.md
site/content/3.10/develop/http/databases.md
site/content/3.11/concepts/data-structure/databases.md
site/content/3.11/develop/http/databases.md
site/content/3.12/concepts/data-structure/databases.md
site/content/3.12/develop/http/databases.md

It's more appropriate to talk about URL-requirements of the API in the API docs instead of the general explanation about databases.
- 3.10:
- 3.11:
- 3.12:

Move info about database context to HTTP API description

---

site/themes/arangodb-docs-theme/layouts/_default/single.html
site/themes/arangodb-docs-theme/static/js/theme.js

modified the scrollToOpenApiFragment function to handle any fragment scrolling beahviour as scrollToFragment().
Include scrollToFragment() call in loadPage() so to handle the fragment scrolling in any kind of page loading
- 3.10:
- 3.11:
- 3.12:

[DOC-587] Fix anchor links scrolling behaviour

---

site/content/3.10/release-notes/version-3.10/whats-new-in-3-10.md
site/content/3.11/release-notes/version-3.10/whats-new-in-3-10.md
site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.10/whats-new-in-3-10.md
site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

Added release notes for metrics that improve observability of the in-memory cache subsystem. 
Relates to https://github.com/arangodb/arangodb/pull/19841 and corresponding backports.
Generated content via https://github.com/arangodb/docs-hugo/pull/248. 
- 3.10:
- 3.11:
- 3.12:

Release notes: more cache metrics

---

.circleci/base_config.yml
.circleci/generate_config.py

fix release generate

---

site/content/3.10/develop/integrations/arangodb-datasource-for-apache-spark.md
site/content/3.11/develop/integrations/arangodb-datasource-for-apache-spark.md
site/content/3.12/develop/integrations/arangodb-datasource-for-apache-spark.md

Dropped support for Spark 2.4 in ArangoDB Spark Datasource.

[DE-691] Spark Datasource: dropped support for Spark 2.4

---

site/content/3.10/index-and-search/indexing/index-basics.md
site/content/3.10/index-and-search/indexing/working-with-indexes/_index.md
site/content/3.11/index-and-search/indexing/index-basics.md
site/content/3.11/index-and-search/indexing/working-with-indexes/_index.md
site/content/3.12/index-and-search/indexing/index-basics.md
site/content/3.12/index-and-search/indexing/working-with-indexes/_index.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

Docs PR for https://github.com/arangodb/arangodb/pull/19938
- 3.10: -
- 3.11: - 
- 3.12: https://github.com/arangodb/arangodb/pull/19938

update release notes for `_id` in stored values

---

toolchain/docker/Dockerfile

- 3.10: arangodb/enterprise-preview:3.10-nightly
- 3.11: arangodb/enterprise-preview:3.11-nightly
- 3.12: arangodb/enterprise-preview:devel-nightly

[DOC-605] Use golang latest image in docs docker images

---

site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

Added release notes for https://github.com/arangodb/arangodb/pull/19882
- 3.10:
- 3.11:
- 3.12:

Release notes: Cluster-internal connectivity checks

---

toolchain/docker/Dockerfile
toolchain/scripts/toolchain.sh

[DOC-604] Download always latest oasisctl tag in Dockerfile

---

site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

Added release notes.
- 3.10:
- 3.11:
- 3.12: https://github.com/arangodb/arangodb/pull/19928

`--database.extended-names` enabled by default

---

.circleci/base_config.yml

This PR changes the git clone step in the plain-build CircleCI Workflow.
Insted of just cloning the target branch, will clone the target branch and locally tag it as a new branch in a detached head state.
This allows to be able to run the plain-build on PRs coming from forks too as they are in a **pull/{NUMBER}/head**.
Without this PR the forked PRs would not be able to build
- 3.10:
- 3.11:
- 3.12:

Enable Forked Repo PR on CircleCI

---

site/content/3.12/components/tools/arangodump/examples.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

This is the documentation for the feature PR: 
- https://github.com/arangodb/arangodb/pull/20021
The description can be found [here](https://github.com/arangodb/arangodb/pull/20021)
- 3.12: Will be available for 3.12 and newer versions.

[BTS-1602] Add --ignore-collection flag to arangodump

---

site/themes/arangodb-docs-theme/static/js/theme.js

Remove anchor from target URL before comparing to responseURL
This check determines whether Netlify responded with a redirect but it had false-positives for URLs with fragment identifier
- 3.10:
- 3.11:
- 3.12:

Fix linking to anchors

---

site/themes/arangodb-docs-theme/layouts/partials/shortcodes/version.html

For example, https://docs.arangodb.com/devel/release-notes/version-3.11/ incorrectly reports "ArangoDB v3.11 is under development ..."
The version matching used the stringified Page object which is like `Page(/the/path)` and in case of the Release Notes, we have `3.11` in the path after the `3.12/` version folder, which made the template logic pick 3.11 instead of the correct version.
- 3.10:
- 3.11:
- 3.12: arangodb/enterprise-preview:devel-nightly

Compare version name against `.Page.Type` to avoid false matches with Release Notes

---

site/content/3.10/concepts/data-structure/documents/_index.md
site/content/3.10/develop/http-api/collections.md
site/content/3.10/develop/javascript-api/@arangodb/collection-object.md
site/content/3.10/develop/javascript-api/@arangodb/db-object.md
site/content/3.11/concepts/data-structure/documents/_index.md
site/content/3.11/develop/http-api/collections.md
site/content/3.11/develop/javascript-api/@arangodb/collection-object.md
site/content/3.11/develop/javascript-api/@arangodb/db-object.md
site/content/3.12/concepts/data-structure/documents/_index.md
site/content/3.12/develop/http-api/collections.md
site/content/3.12/develop/javascript-api/@arangodb/collection-object.md
site/content/3.12/develop/javascript-api/@arangodb/db-object.md

~To be applied to 3.10 and 3.11 after review~
- 3.10:
- 3.11:
- 3.12:

DOC-621 | Warn about mixing user-specified and auto-generated keys for a collection with 2+ shards

---

site/content/3.10/concepts/data-structure/documents/_index.md
site/content/3.10/develop/http-api/documents.md
site/content/3.11/concepts/data-structure/documents/_index.md
site/content/3.11/develop/http-api/documents.md
site/content/3.12/concepts/data-structure/documents/_index.md
site/content/3.12/develop/http-api/documents.md

Document API was unclear for the `_id` and `_key` fields use cases

Improve Document API

---

site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

DOC-608 | APM-660 | Release notes for memory accounting metrics and memory usage improvements

---

site/content/3.10/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
site/content/3.10/develop/integrations/kafka-connect-arangodb-sink-connector/configuration.md
site/content/3.11/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
site/content/3.11/develop/integrations/kafka-connect-arangodb-sink-connector/configuration.md
site/content/3.12/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
site/content/3.12/develop/integrations/kafka-connect-arangodb-sink-connector/configuration.md

Updated the documentation of Kafka Connector with batch writes.

[DE-627] Kafka Connector: batch writes

---

toolchain/scripts/toolchain.sh

Fix the following CircleCI error in scheduled workflow:
```
toolchain  | [arangodb/enterprise-preview:3.10-nightly 3.10] [run_arangodb_container] Run cluster server
toolchain  | 7976000485ac10583752d694c8ab2a2633d9d83e78689c581291883b7dedd3dc
...
toolchain  | Error response from daemon: Container 7976000485ac10583752d694c8ab2a2633d9d83e78689c581291883b7dedd3dc is not running
toolchain  | [arangodb/enterprise-preview:3.10-nightly 3.10] [generate_optimizer_rules] [ERROR] 
toolchain  | [arangodb/enterprise-preview:3.10-nightly 3.10] [generate_optimizer_rules] Done
```
- 3.10: arangodb/enterprise-preview:3.10-nightly
- 3.11: arangodb/enterprise-preview:3.11-nightly
- 3.12: arangodb/enterprise-preview:devel-nightly

Toolchain: Wait for cluster and single server until they are ready

---

site/themes/arangodb-docs-theme/layouts/partials/search.html

Prevents the docs from remaining hidden because of an error in theme.js as the result of e.g. the browser blocking the load of the docsearch script
- 3.10:
- 3.11:
- 3.12:

Check whether docsearch is defined before calling it

---

site/content/3.10/develop/drivers/java/_index.md
site/content/3.11/develop/drivers/java/_index.md
site/content/3.12/develop/drivers/java/_index.md

Disclaimer about serialization of data definitions classes in Java Driver.

Java Driver: data definitions classes serialization disclaimer

---

site/content/3.10/data-science/adapters/arangordf-adapter/_index.md
site/content/3.11/data-science/adapters/arangordf-adapter/_index.md
site/content/3.12/data-science/adapters/arangordf-adapter/_index.md

ref: https://github.com/ArangoDB-Community/ArangoRDF/releases/tag/0.1.0
The ArangoRDF specification has changed as of ArangoRDF [0.1.0](https://github.com/ArangoDB-Community/ArangoRDF/releases/tag/0.1.0) (released Monday Dec 4 2023).
This PR addresses the changes required to keep its doc page up to date
- 3.10:
- 3.11:
- 3.12:

Update ArangoRDF doc page

---

site/themes/arangodb-docs-theme/layouts/shortcodes/metrics.md

Make metric categories visible in ToC again
https://deploy-preview-383--docs-hugo.netlify.app/devel/develop/http-api/monitoring/metrics/
- 3.10:
- 3.11:
- 3.12:

Fix headline levels for metrics, trim trailing dot

---

site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

arangoimport's `--type` option has been changed from `json` to `auto`; it can automatically detect the import file format.
- 3.10:
- 3.11:
- 3.12: https://github.com/arangodb/arangodb/pull/20248

Release notes: arangoimport auto detects the import file format

---

site/content/3.10/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md

Removed `asyncExecutor()` configuration method, since deprecated since https://github.com/arangodb/arangodb-java-driver/commit/81a15993e20b2e49b01060fe095d6e7a16e70eeb

[DE-726] removed deprecated asyncExecutor (DE-726)

---

site/content/3.10/arangograph/data-loader/example.md
site/content/3.11/arangograph/data-loader/example.md
site/content/3.12/arangograph/data-loader/example.md

Add download link to Data Loader example files.

Add download link to Data Loader example files

---

site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

Added `arangodb_aql_cursors_memory_usage` metric to the memory accounting list.
- 3.10:
- 3.11:
- 3.12: https://github.com/arangodb/arangodb/pull/20215

Added `arangodb_aql_cursors_memory_usage` metric to memory accounting list

---

site/content/3.10/about-arangodb/features/community-edition.md
site/content/3.10/about-arangodb/features/highlights-by-version.md
site/content/3.10/about-arangodb/use-cases.md
site/content/3.10/components/arangodb-server/storage-engine.md
site/content/3.10/deploy/architecture/_index.md
site/content/3.10/develop/transactions/limitations.md
site/content/3.10/release-notes/version-3.6/incompatible-changes-in-3-6.md
site/content/3.11/about-arangodb/features/community-edition.md
site/content/3.11/about-arangodb/features/highlights-by-version.md
site/content/3.11/about-arangodb/use-cases.md
site/content/3.11/components/arangodb-server/storage-engine.md
site/content/3.11/deploy/architecture/_index.md
site/content/3.11/develop/transactions/limitations.md
site/content/3.11/release-notes/version-3.6/incompatible-changes-in-3-6.md
site/content/3.12/about-arangodb/features/community-edition.md
site/content/3.12/about-arangodb/features/highlights-by-version.md
site/content/3.12/about-arangodb/use-cases.md
site/content/3.12/components/arangodb-server/storage-engine.md
site/content/3.12/deploy/architecture/_index.md
site/content/3.12/develop/transactions/limitations.md
site/content/3.12/release-notes/version-3.6/incompatible-changes-in-3-6.md

Moved the Storage engine content under ArangoDB Server.

DOC-626 | Move storage engine content under ArangoDB Server

---

site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

- https://github.com/arangodb/arangodb/pull/19715
- https://github.com/arangodb/arangodb/pull/20402
- 3.10:
- 3.11:
- 3.12:

DOC-614 | Protocol aliases for endpoints

---

site/content/3.11/develop/http-api/queries/aql-queries.md
site/content/3.12/develop/http-api/queries/aql-queries.md

DOC-647 | Clarify the presence of `nextBatchId`

---

site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

See https://github.com/arangodb/arangodb/pull/20343
- 3.10:
- 3.11:
- 3.12:

Release notes: Improved `move-filters-into-enumerate` optimizer rule

---

site/content/3.10/release-notes/version-3.10/incompatible-changes-in-3-10.md
site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md

Since we don't currently document exit codes, I don't see a point of telling users the exact ones that some errors now set instead of 1. I considered linking to https://github.com/arangodb/arangodb/blob/devel/lib/Basics/exitcodes.dat but we would need to adjust the link for the release to 3.12 and you can also figure out what the exit codes mean based on the error messages you get if a fatal error occurs.
- 3.10:
- 3.11:
- 3.12:

DOC-614 | Some arangod exit codes changed

---

site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md

I'm not sure whether we should mention this as an API change because this is actually bug fix
- 3.10:
- 3.11:
- 3.12:

DOC-614 | Mention extended edge update validation in Gharial

---

site/content/3.12/develop/http-api/administration.md
site/content/3.12/operations/administration/configuration.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

`type: object` leads to only **Response Body** be rendered (after the response description). This is okay IMO, but it would be nicer if we could properly document endpoints like these using `patternProperties` and then a structured description of the sub-objects currently explained in free-text
No curl examples added because of potentially sensitive information in the reply / extremely long output.
Preview: https://deploy-preview-425--docs-hugo.netlify.app/devel/develop/http-api/administration/#get-the-startup-option-configuration
- 3.10:
- 3.11:
- 3.12:

DOC-614 | Add Options API

---

site/themes/arangodb-docs-theme/layouts/_default/_markup/render-codeblock-openapi.html

This removes dumping the Go data structure for `type: array` (indirectly checked by looking for `items:`) at the top-level of a response schema description.
If no item type is defined for an array, still render the property (with an indicated type of `array`).
For arrays with a defined item type (excluding `items: type: ''`), display `array<type>` instead of `[type]`.
Empty item type, `array`:
- Before https://docs.arangodb.com/stable/develop/http-api/queries/aql-queries/#create-a-cursor_res_201_result
- After https://deploy-preview-427--docs-hugo.netlify.app/stable/develop/http-api/queries/aql-queries/#create-a-cursor_res_201_result
No debug-dumping of top-level arrays, `array<object>` instead of `[object]`:
- Before <https://docs.arangodb.com/stable/develop/http-api/queries/aql-queries/# …

Do not debug-dump for top-level arrays & improve array rendering in OpenAPI responses

---

site/content/3.10/aql/high-level-operations/replace.md
site/content/3.10/aql/high-level-operations/update.md
site/content/3.11/aql/high-level-operations/replace.md
site/content/3.11/aql/high-level-operations/update.md
site/content/3.12/aql/high-level-operations/replace.md
site/content/3.12/aql/high-level-operations/update.md

Reported by @ile
- 3.10:
- 3.11:
- 3.12:

Improve lead paragraphs of the AQL UPDATE and REPLACE operations

---

site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

https://github.com/arangodb/arangodb/pull/20324
- 3.10:
- 3.11:
- 3.12:

DOC-614 | V8 upgrade to v12

---

site/content/3.10/release-notes/version-3.10/api-changes-in-3-10.md
site/content/3.11/release-notes/version-3.10/api-changes-in-3-10.md
site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md

Relates to https://github.com/arangodb/arangodb/pull/18516 and backports.
Added release notes. 
Unclear why the response body of  `GET /_api/index` endpoint is not documented in the first place. To add the new `progress` attribute returned by this endpoint in the HTTP API docs, the endpoint description needs to be reworked and include the response body.

DOC-614 | Progress indication for index generation

---

site/themes/arangodb-docs-theme/static/js/theme.js

Scrolling the table of contents into view can lead to the page scrolling on its own (depends on viewport size and ToC length) because of a scroll event loop caused by the main content getting scrolled and not the ToC container only
This PR disables the ToC scrolling as a workaround
- 3.10:
- 3.11:
- 3.12:

DOC-649 | Disable ToC scroll into view, throttle scroll events

---

site/content/3.10/arangograph/security-and-access-control/_index.md
site/content/3.11/arangograph/security-and-access-control/_index.md
site/content/3.12/arangograph/security-and-access-control/_index.md

Added note to clarify that permissions differ between organization owners and organization members. Fixed some typos and formatting.

DOC-656 | Clarify AG org owner and member permissions

---

site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md

- https://github.com/arangodb/arangodb/pull/20512
- https://github.com/arangodb/arangodb/pull/20541/commits/3a6520c10b2dc8b818e83086b05d16ae5da54f1d#diff-df98ba6a30c47b0a44759fde6294d15e2bb88d5df34e751d35b2a9fd032775adL62-R62
- https://github.com/arangodb/arangodb/pull/20437
- https://github.com/arangodb/arangodb/pull/20504
- 3.10:
- 3.11:
- 3.12:

DOC-614 | Changed startup option defaults, audit log escaping, cluster compaction

---

site/content/3.10/arangograph/deployments/_index.md
site/content/3.11/arangograph/deployments/_index.md
site/content/3.12/arangograph/deployments/_index.md

DOC-663 | Add missing info on autologin feature and private endpoints in AG

---

site/themes/arangodb-docs-theme/static/css/theme.css

Experimental change to fix code overflow in "Show details" for https://docs.arangodb.com/3.11/components/arangodb-server/options/#--auditwrite-log-level
Need to verify that this doesn't wrap code in bad ways, like in the middle of words
- 3.10:
- 3.11:
- 3.12:

Pre-wrap more code to avoid layout overflow

---

site/content/3.10/develop/http-api/collections.md
site/content/3.10/develop/http-api/databases.md
site/content/3.10/develop/javascript-api/@arangodb/collection-object.md
site/content/3.10/develop/javascript-api/@arangodb/db-object.md
site/content/3.11/develop/http-api/collections.md
site/content/3.11/develop/http-api/databases.md
site/content/3.11/develop/javascript-api/@arangodb/collection-object.md
site/content/3.11/develop/javascript-api/@arangodb/db-object.md
site/content/3.12/develop/http-api/collections.md
site/content/3.12/develop/http-api/databases.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md

- Changed 3.10 and 3.11 API docs to reflect that the prototype collection controls the writeConcern
- Added explanation of the default value inheritance
- Added release notes about the writeConcern now being independent of the prototype collection
- 3.10:
- 3.11:
- 3.12:

DOC-614 | Adjustable writeConcern

---

site/content/3.12/develop/drivers/java/reference-version-6/driver-setup.md
site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.12/develop/integrations/arangodb-datasource-for-apache-spark.md

Active failover deployment is not supported in 3.12 and, therefore, must not be mentioned in the documentation.

remove mentions of active failover delpoyment in 3.12

---

toolchain/scripts/generators/oasisctl.py

- Fix title and menuTitle substitutions
- Suppress lead paragraph (adds no value)
- Don't capitalize command in headline as this is misleading
- 3.10:
- 3.11:
- 3.12:

Make oasisctl content slightly less redundant & fix titles

---

site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
site/content/4.0/develop/drivers/java/reference-version-7/driver-setup.md

Updated documentation about connection TTL in the Java driver.

[DE-794] Java Driver: connection TTL

---

site/data/versions.yaml
site/themes/arangodb-docs-theme/layouts/partials/deprecated.html
site/themes/arangodb-docs-theme/layouts/partials/shortcodes/card.html
site/themes/arangodb-docs-theme/static/js/theme.js

To be published on 2024-04-15 (3.10 EoL date).
Fixes link aliasing including the deprecation admonition, as well as the link handling for cards (soft navigation)
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-609 | DOC-670 | Mark 3.10 as deprecated, fix cards and link aliases

---

site/content/3.10/components/tools/arangodb-starter/architecture.md
site/content/3.10/concepts/data-structure/documents/schema-validation.md
site/content/3.10/release-notes/version-3.10/known-issues-in-3-10.md
site/content/3.11/components/tools/arangodb-starter/architecture.md
site/content/3.11/concepts/data-structure/documents/schema-validation.md
site/content/3.11/release-notes/version-3.10/known-issues-in-3-10.md
site/content/3.11/release-notes/version-3.11/known-issues-in-3-11.md
site/content/3.12/components/tools/arangodb-starter/architecture.md
site/content/3.12/concepts/data-structure/documents/schema-validation.md
site/content/3.12/release-notes/version-3.10/known-issues-in-3-10.md
site/content/3.12/release-notes/version-3.11/known-issues-in-3-11.md
site/content/3.12/release-notes/version-3.12/known-issues-in-3-12.md
site/content/3.13/components/tools/arangodb-starter/architecture.md
site/content/3.13/concepts/data-structure/documents/schema-validation.md
site/content/3.13/release-notes/version-3.10/known-issues-in-3-10.md
site/content/3.13/release-notes/version-3.11/known-issues-in-3-11.md
site/content/3.13/release-notes/version-3.12/known-issues-in-3-12.md
site/content/3.13/release-notes/version-3.13/known-issues-in-3-13.md

Remove KIs and mention limitations/properties in the schema validation page
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Integrate KIs into schema validation docs

---

site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md

https://arangodb.atlassian.net/browse/DOC-684
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-684 | Default server language changed

---

site/themes/arangodb-docs-theme/layouts/partials/inkeep-widget.html

Bump the inkeep chat widget to the latest version (`0.2.278`).
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Bump inkeep widgets version

---

.gitignore
site/content/3.10/deploy/active-failover/using-the-arangodb-starter.md
site/content/3.10/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.10/deploy/single-instance/using-the-arangodb-starter.md
site/content/3.11/deploy/active-failover/using-the-arangodb-starter.md
site/content/3.11/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.11/deploy/single-instance/using-the-arangodb-starter.md
site/content/3.12/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.12/deploy/single-instance/using-the-arangodb-starter.md
site/content/3.13/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.13/deploy/single-instance/using-the-arangodb-starter.md

Due to the latest changes in Docker Network Mode, we need to explicitly specify the network mode in older starter versions

BTS-1863 Update starter doc for the latest Docker changes

---

site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.11/incompatible-changes-in-3-11.md
site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/release-notes/version-3.11/incompatible-changes-in-3-11.md
site/content/3.13/release-notes/version-3.11/whats-new-in-3-11.md
site/content/3.13/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Release notes for switch from libmusl to glibc

---

site/content/3.10/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.11/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.13/develop/drivers/java/reference-version-7/driver-setup.md

documented HTTP protocol configuration to reuse Vert.x instance
- https://github.com/arangodb/arangodb-java-driver/pull/558

[DE-535] Java Driver: configure Vert.x instance

---

site/static/_redirects

The master service agreements still use the obsolete link that is broken since at least 2020.
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Redirect from /latest to /stable

---

site/content/3.10/develop/integrations/spring-data-arangodb/_index.md
site/content/3.10/develop/integrations/spring-data-arangodb/reference-version-4/mapping/_index.md
site/content/3.11/develop/integrations/spring-data-arangodb/_index.md
site/content/3.11/develop/integrations/spring-data-arangodb/reference-version-4/mapping/_index.md
site/content/3.12/develop/integrations/spring-data-arangodb/_index.md
site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-4/mapping/_index.md
site/content/3.13/develop/integrations/spring-data-arangodb/_index.md
site/content/3.13/develop/integrations/spring-data-arangodb/reference-version-4/mapping/_index.md

Spring Data: documented object mapping behavior

[DE-539] Spring Data: documented object mapping behavior

---

site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-667 | `--server.max-number-detached-threads` obsolete

---

site/content/3.12/develop/http-api/collections.md
site/content/3.13/develop/http-api/collections.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

BTS-1915: recalculateCount response doesn't include "count" in cluster

---

site/content/3.12/aql/graphs/traversals.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/aql/graphs/traversals.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

AQL traversals: Initial index hint support

---

site/content/3.10/index-and-search/arangosearch/search-alias-views-reference.md
site/content/3.11/index-and-search/arangosearch/search-alias-views-reference.md
site/content/3.12/index-and-search/arangosearch/search-alias-views-reference.md
site/content/3.13/index-and-search/arangosearch/search-alias-views-reference.md

Make it easier to discover the limitations for `search-alias`  Views which were only covered in the inverted index page
https://github.com/arangodb/arangodb/issues/21104#issuecomment-2196862390
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Add cross-reference about inverted index restrictions when combining them in a search-alias View

---

site/content/3.12/release-notes/_index.md
site/content/3.13/release-notes/_index.md
site/themes/arangodb-docs-theme/layouts/shortcodes/full-version.html

Due to trunk-based development, there is no 3.12 upstream branch but only release branches (3.12.0 etc.). Create this particular link dynamically using the version information to have it update automatically.
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Construct 3.12 CHANGELOG link with shortcode

---

site/content/3.11/arangograph/security-and-access-control/_index.md
site/content/3.12/arangograph/security-and-access-control/_index.md
site/content/3.13/arangograph/security-and-access-control/_index.md

Adds Microsoft as an allowed authentication provider. 
Currently this documentation only lists github and google although microsoft is already allowed via oasisctl.
Did not add for version 3.10 since it is no longer available on ArangoGraph
- 3.11: 
- 3.12: 
- 3.13:

add --enable-microsoft to arangograph authentication providers

---

site/content/3.11/arangograph/security-and-access-control/single-sign-on/_index.md
site/content/3.12/arangograph/security-and-access-control/single-sign-on/_index.md
site/content/3.13/arangograph/security-and-access-control/single-sign-on/_index.md

Add clarification that only SP-Initiated SSO is available in ArangoGraph.
Remove comment about SCIM as it is no longer necessary. With current ArangoGraph SSO implementation, individual users do not need to be provisioned. All users from the allowed domain will have an account created in the organization but with no default permissions.
- 3.11: 
- 3.12: 
- 3.13:

add warning that IdP-Initiated SSO is not allowed

---

site/content/3.11/develop/http-api/general-request-handling.md
site/content/3.11/release-notes/deprecated-and-removed-features.md
site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
site/content/3.12/release-notes/version-3.11/incompatible-changes-in-3-11.md
site/content/3.13/release-notes/version-3.11/incompatible-changes-in-3-11.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-707 | Deprecation of VelocyStream for v3.11

---

site/content/3.11/develop/http-api/jobs.md
site/content/3.12/develop/http-api/jobs.md
site/content/3.13/develop/http-api/jobs.md
site/themes/arangodb-docs-theme/layouts/_default/_markup/render-codeblock-openapi.html

~TODO: Clarify if job results can have a different status code than 202 Accepted in the success case~ yes
https://arangodb.slack.com/archives/C06HYC4KBFF/p1723020907612789
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Add OpenAPI default response to cover finished async jobs

---

site/content/3.11/develop/http-api/collections.md
site/content/3.12/develop/http-api/collections.md
site/content/3.13/develop/http-api/collections.md

- The `result` attribute is an array of objects, not an object when listing collections
- Backport improvements and fixes about the collection API to 3.11. Adjusted for difference in 3.11 where the `writeConcern` cannot be adjusted if `distributeShardsLike` is used
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Fix response description for listing collections / backports to 3.11

---

site/content/3.12/develop/http-api/monitoring/logs.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/develop/http-api/monitoring/logs.md
site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

https://github.com/arangodb/arangodb/pull/21235
HTTP API Preview: https://deploy-preview-598--docs-hugo.netlify.app/stable/develop/http-api/monitoring/logs/#get-the-server-log-levels_query_withAppenders
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-699 | Individual log levels for log outputs

---

site/content/3.11/develop/http-api/indexes/_index.md
site/content/3.11/index-and-search/indexing/working-with-indexes/_index.md
site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
site/content/3.12/develop/http-api/indexes/_index.md
site/content/3.12/index-and-search/indexing/working-with-indexes/_index.md
site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
site/content/3.13/develop/http-api/indexes/_index.md
site/content/3.13/index-and-search/indexing/working-with-indexes/_index.md
site/content/3.13/release-notes/version-3.11/api-changes-in-3-11.md

3.11 API changes: inverted index caching, re-order, add internal indexes remark
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-712 | Caching-related API changes to inverted index missing in 3.11 release notes

---

site/content/3.12/develop/drivers/java/reference-version-6/driver-setup.md
site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
site/content/3.13/develop/drivers/java/reference-version-6/driver-setup.md
site/content/3.13/develop/drivers/java/reference-version-7/changes-in-version-7.md
site/content/3.13/develop/drivers/java/reference-version-7/driver-setup.md

Java Driver: removed mentions to VST in ArangoDB 3.12+

[DOC-708] Java Driver: removed mentions to VST in ArangoDB 3.12+

---

site/themes/arangodb-docs-theme/layouts/_default/_markup/render-codeblock-openapi.html
site/themes/arangodb-docs-theme/static/css/theme.css

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Use Hugo instead of CSS to capitalize HTTP API methods

---

site/content/3.10/develop/http-api/collections.md
site/content/3.11/develop/http-api/collections.md
site/content/3.12/develop/http-api/collections.md
site/content/3.13/develop/http-api/collections.md

Simple fix. The expression does not need a "be" verb.

Fixing typo in collections API

---

site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

New AQL optimizer rule `replace-entries-with-object-iteration`
https://github.com/arangodb/arangodb/pull/21186
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Fast object enumeration with `ENTRIES()`

---

site/content/3.11/aql/operators.md
site/content/3.12/aql/operators.md
site/content/3.13/aql/operators.md

This is according to the GFM spec, https://github.com/yuin/goldmark/issues/194
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Escape `|` in table even if it's in inline code

---

site/content/3.12/_index.md
site/content/3.12/components/arangodb-server/environment-variables.md
site/content/3.13/components/arangodb-server/environment-variables.md
toolchain/arangoproxy/internal/init.go
toolchain/scripts/toolchain.sh

Test whether 3.12 compiles with 3.11 LDAP fix.
This revealed that arangoproxy can hang if arangosh fails to start e.g. due to a missing `icudtl_legacy.dat`.
Add a missing `cmd.Wait()` which is apparently required on Unix so that a failed arangosh doesn't linger around as a zombie process and report a non-zero exit code. Also log stderr output.
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Fix 3.12 example generation with self-compiled ArangoDB

---

site/content/3.11/aql/execution-and-performance/explaining-queries.md
site/content/3.11/aql/how-to-invoke-aql/with-arangosh.md
site/content/3.11/develop/http-api/administration.md
site/content/3.11/develop/http-api/graphs/edges.md
site/content/3.11/develop/http-api/indexes/_index.md
site/content/3.11/develop/http-api/queries/aql-queries.md
site/content/3.11/develop/javascript-api/@arangodb/collection-object.md
site/content/3.11/develop/transactions/stream-transactions.md
site/content/3.12/aql/execution-and-performance/explaining-queries.md
site/content/3.12/aql/how-to-invoke-aql/with-arangosh.md
site/content/3.12/develop/http-api/administration.md
site/content/3.12/develop/http-api/graphs/edges.md
site/content/3.12/develop/http-api/indexes/_index.md
site/content/3.12/develop/http-api/queries/aql-queries.md
site/content/3.12/develop/javascript-api/@arangodb/collection-object.md
site/content/3.12/develop/transactions/stream-transactions.md
site/content/3.13/aql/execution-and-performance/explaining-queries.md
site/content/3.13/aql/how-to-invoke-aql/with-arangosh.md
site/content/3.13/develop/http-api/administration.md
site/content/3.13/develop/http-api/graphs/edges.md
site/content/3.13/develop/http-api/indexes/_index.md
site/content/3.13/develop/http-api/queries/aql-queries.md
site/content/3.13/develop/javascript-api/@arangodb/collection-object.md
site/content/3.13/develop/javascript-api/@arangodb/db-object.md
site/content/3.13/develop/transactions/stream-transactions.md

Also add internal remarks that certain methods / endpoints and properties in the HTTP API are undocumented on purpose
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

JS API: collection.truncate() takes options

---

site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

Yen's algorithm and neighbor caching to get 3.10 performance back
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-719 | Add graph query algorithm improvements to release notes

---

site/content/3.11/develop/http-api/queries/aql-queries.md
site/content/3.12/develop/http-api/queries/aql-queries.md
site/content/3.13/develop/http-api/queries/aql-queries.md

Small typo fix. The docs should refer to "collections", as the term is used throughout the sentence.

Collections API

---

site/content/3.12/develop/transactions/stream-transactions.md
site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/develop/transactions/stream-transactions.md
site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

Default max size for Stream Transactions increased from 128 to 512 MiB
- https://github.com/arangodb/arangodb/pull/21553
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Update Stream Transaction default size

---

site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/release-notes/version-3.12/api-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

https://github.com/arangodb/arangodb/pull/21447
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Add a cluster transaction metric

---

.circleci/generate_config.py

3.11 now has dedicated images because we moved to clang-19 for devel (3.12.5+)
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

CircleCI: Update build images for 3.11 and devel

---

site/themes/arangodb-docs-theme/layouts/partials/inkeep-widget.html
site/themes/arangodb-docs-theme/static/css/theme.css

This avoids an overlap with HubSpot.
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-739 | Move Inkeep Ask AI button

---

site/content/3.11/operations/upgrading/_index.md
site/content/3.12/operations/upgrading/_index.md
site/content/3.13/operations/upgrading/_index.md

They replace the regular upgrading procedure due to the number and string sorting issues
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Cross-reference special upgrade procedures for 3.11 and 3.12

---

site/content/3.11/develop/http-api/collections.md
site/content/3.11/develop/javascript-api/@arangodb/collection-object.md
site/content/3.12/develop/http-api/collections.md
site/content/3.12/develop/javascript-api/@arangodb/collection-object.md
site/content/3.13/develop/http-api/collections.md
site/content/3.13/develop/javascript-api/@arangodb/collection-object.md

* Describe the schema validation sub-properties
* Add missing RocksDB figures (thanks @Burlango for pointing this out)
* Add status / statusString properties to 3.11 and 3.12, but not in 3.13 to move forward with the deprecation
* Add code comments about purposefully undocumented properties
* Fix response description for the endpoint to rename collections
TODO: The windowed cache hit-rate seems to remain 0 at all times, bug? https://arangodb.atlassian.net/browse/BTS-2101
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Add missing collection properties

---

redocly.yaml
site/content/3.11/develop/http-api/collections.md
site/content/3.11/develop/http-api/foxx.md
site/content/3.11/develop/http-api/queries/aql-queries.md
site/content/3.11/develop/http-api/tasks.md
site/content/3.11/develop/http-api/users.md
site/content/3.11/develop/http-api/views/search-alias-views.md
site/content/3.12/develop/http-api/collections.md
site/content/3.12/develop/http-api/foxx.md
site/content/3.12/develop/http-api/queries/aql-queries.md
site/content/3.12/develop/http-api/tasks.md
site/content/3.12/develop/http-api/users.md
site/content/3.12/develop/http-api/views/search-alias-views.md
site/content/3.13/develop/http-api/collections.md
site/content/3.13/develop/http-api/foxx.md
site/content/3.13/develop/http-api/queries/aql-queries.md
site/content/3.13/develop/http-api/tasks.md
site/content/3.13/develop/http-api/users.md
site/content/3.13/develop/http-api/views/search-alias-views.md
toolchain/arangoproxy/internal/service/service.go

Fix a couple of issues reported by Swagger Editor web service as well as by the Redocly CLI linter.
Extend metadata. Before:
```json
{
"info": {
"description": "ArangoDB REST API Interface",
"title": "ArangoDB",
"version": "3.12.4"
}
}
```
After (3.10 and 3.11 have Apache 2.0 license set accordingly):
```json
{
"externalDocs": {
"description": "ArangoDB Documentation",
"url": "https://docs.arangodb.com"
},
"info": {
"contact": {
"name": "ArangoDB Inc.",
"url": "https://arangodb.com"
},
"license": {
"name": "Business Source License 1.1",
"url": "https://github.com/arangodb/arangodb/blob/devel/LICENSE"
},
"summary": "The RESTful HTTP API of the ArangoDB Core Database System",
"title": "ArangoDB Core API",
"version": "3.12.4"
},
```
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Fix OpenAPI validation errors and add more metadata

---

site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
site/content/3.13/release-notes/version-3.12/incompatible-changes-in-3-12.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Add remark to use kube-arangodb 1.2.47+ for upgrading 3.12.2/3.12.3

---

site/content/3.11/develop/http-api/graphs/named-graphs.md
site/content/3.11/graphs/general-graphs/management.md
site/content/3.12/develop/http-api/graphs/named-graphs.md
site/content/3.12/graphs/general-graphs/management.md
site/content/3.13/develop/http-api/graphs/named-graphs.md
site/content/3.13/graphs/general-graphs/management.md

And removing edges may remove other edges if the former are used as vertices - it seems to work differently than documented though (non-recursive?) -> It only deleted incoming and outgoing edges for both vertices and edges, non-recursively
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-746 | Removing vertices with Gharial deletes its edges

---

site/content/3.13/data-science/_index.md
site/content/3.13/graphs/graph-analytics.md

Move Graph analytics page in the Graph chapter, it is not part of the GenAI suite.

Move Graph analytics page in the Graph chapter

---

site/content/3.12/develop/http-api/monitoring/logs.md
site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
site/content/3.13/develop/http-api/monitoring/logs.md
site/content/3.13/release-notes/version-3.12/whats-new-in-3-12.md

Follow-up to https://github.com/arangodb/docs-hugo/pull/711
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-745 | Fix API call recording OpenAPI description and release notes

---

site/content/3.13/graphs/graph-visualizer.md

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-769 | Graph Visualizer Canvas Actions and UI updates

---

site/content/3.12/graphs/_index.md
site/content/3.13/graphs/_index.md

Agreed that for the time being we should only rename the menu title and not the URL(s) as this will lead to extra effort, maintenance, and plenty of external broken links (from main website, readmes, and other ArangoDB resources).

Rename menu title to Graph Intelligence

---

site/content/3.12/components/tools/arangodb-starter/options.md
site/content/3.12/deploy/cluster/deployment/manual-start.md
site/content/3.12/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.12/deploy/single-instance/manual-start.md
site/content/3.12/operations/installation/docker.md
site/content/3.13/components/tools/arangodb-starter/options.md
site/content/3.13/deploy/cluster/deployment/manual-start.md
site/content/3.13/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.13/deploy/single-instance/manual-start.md
site/content/3.13/operations/installation/docker.md
toolchain/scripts/toolchain.sh

In v3.12.5+, `arangodb/arangodb` images no longer published, use `arangodb/enterprise`
Change in Starter TBD:
- https://github.com/arangodb-helper/arangodb/pull/457
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Update references to directly published Docker images

---

site/content/3.12/deploy/cluster/deployment/using-the-arangodb-starter.md
site/content/3.13/deploy/cluster/deployment/using-the-arangodb-starter.md

Follow-up to #727
Adam said the upstream PR would be invalid. At the very least, it is not merged yet, so we can't say that the default for `--docker.image` would be `arangodb/enterprise:latest`.
- https://github.com/arangodb-helper/arangodb/pull/457
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Starter still defaults to `arangodb/arangodb:latest`

---

.circleci/config.yml

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

CircleCI: Actually retry curl (capture error)

---

site/themes/arangodb-docs-theme/layouts/partials/version-selector.html
site/themes/arangodb-docs-theme/static/js/theme.js

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-789 | Remove 3.9 and 3.8 from version selector

---

site/themes/arangodb-docs-theme/layouts/404.html
site/themes/arangodb-docs-theme/layouts/_default/baseof.html
site/themes/arangodb-docs-theme/layouts/_default/home.navigation.html
site/themes/arangodb-docs-theme/layouts/_default/home.notfound.html
site/themes/arangodb-docs-theme/layouts/partials/breadcrumbs.html
site/themes/arangodb-docs-theme/layouts/partials/header.html
site/themes/arangodb-docs-theme/layouts/partials/search.html
site/themes/arangodb-docs-theme/layouts/partials/toc.html
site/themes/arangodb-docs-theme/layouts/partials/version-selector.html
site/themes/arangodb-docs-theme/static/css/theme.css
site/themes/arangodb-docs-theme/static/js/theme.js

This avoids potential clashes between the identifiers used in the layout and the fragment IDs created for the content.
It fixes at least one conflict between the #header styling and the Foxx content with a headline "header":
- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

Hugo: Change templating from IDs to classes

---

site/content/3.12/graphs/graph-analytics.md
site/content/3.13/graphs/graph-analytics.md
site/themes/arangodb-docs-theme/layouts/shortcodes/danger.html
site/themes/arangodb-docs-theme/layouts/shortcodes/info.html
site/themes/arangodb-docs-theme/layouts/shortcodes/kbd.html
site/themes/arangodb-docs-theme/layouts/shortcodes/security.html
site/themes/arangodb-docs-theme/layouts/shortcodes/tip.html
site/themes/arangodb-docs-theme/layouts/shortcodes/warning.html
site/themes/arangodb-docs-theme/static/css/theme.css

- 3.10: 
- 3.11: 
- 3.12: 
- 3.13:

DOC-783 | Graph analytics on the ArangoDB Platform
